### ISSUE TITLE
Question: should `meta` be marked as a required property for `/ResourceTypes` discovery endpoint?

### ISSUE THREAD

**Issue by seikenberry9** [suvera/scim2-compliance-test-utility#6]
We are implementing a SCIM server using the [elimity scim](https://github.com/elimity-com/scim) library.  When testing compliance with this utility, the following error is returned for the `/ResourcesTypes` endpoint: `error: object has missing required properties (["meta"])`.  

The SCIM [RFC](https://datatracker.ietf.org/doc/html/rfc7643#section-3.1) seems to read that `meta` is not required to be in the response from discovery endpoints:

> Each SCIM resource (Users, Groups, etc.) includes the following
   common attributes.  With the exception of the "ServiceProviderConfig"
   and "ResourceType" server discovery endpoints and their associated
   resources, these attributes MUST be defined for all resources,
   including any extended resource types.

Should `meta` be required in the response from the discovery endpoint?  Thanks!

**Comment by suvera** [comment]
Yes, in a SCIM 2.0 server response for the `/ResourceTypes` endpoint, the `meta` attribute is mandatory. 

The `meta` attribute provides essential metadata about the resource type itself, such as:

* `resourceType`: The name of the resource type (e.g., "User", "Group").
* `created`: The date and time when the resource type was created.
* `lastModified`: The date and time when the resource type was last modified.
* `location`: The URI of the resource type.

This information is crucial for clients interacting with your SCIM server, as it helps them understand the structure and capabilities of the supported resource types.

**Key Points:**

* **Mandatory:** The SCIM 2.0 specification explicitly states that the `meta` attribute is required for all resource types.
* **Metadata:** The `meta` attribute provides metadata about the resource type, not the individual resources themselves.
* **Client Understanding:** This information helps clients understand the capabilities of your SCIM server and how to interact with the different resource types it supports.

If you omit the `meta` attribute, your SCIM server will not be compliant with the SCIM 2.0 specification, and clients may encounter issues when trying to interact with it.

**Comment by Valodim** [comment]
I'd like disagree here, and bring up some additional points: 

> The `meta` attribute provides essential metadata about the resource type itself, such as:
> 
>     * `resourceType`: The name of the resource type (e.g., "User", "Group").
> 
>     * `created`: The date and time when the resource type was created.
> 
>     * `lastModified`: The date and time when the resource type was last modified.
> 
>     * `location`: The URI of the resource type.

I don't understand in what way any of these attributes would be considered "crucial". None of these fields are necessary to know for a SCIM client to successfully interact with the server. The resourceType and location are redundant information, and I'm not sure what a client would even do with the timestamps. Point in case, the Entra SCIM client works fine without any `meta` attribute present on `ResourceType`s.

> Mandatory: The SCIM 2.0 specification explicitly states that the meta attribute is required for all resource types.

A statement like this should ideally quote where the spec explicitly states, because from what I can see this is just false. The relevant paragraph from the spec was already quoted above:

> Each SCIM resource (Users, Groups, etc.) includes the following
common attributes. With the exception of the "ServiceProviderConfig"
and "ResourceType" server discovery endpoints and their associated
resources, these attributes MUST be defined for all resources,
including any extended resource types.

This very clearly states that the common attributes, to which `meta` belongs, are *not* mandatory for the `ResourceType` resource.

> If you omit the meta attribute, your SCIM server will not be compliant with the SCIM 2.0 specification

This does not follow from the given arguments. For a compliance test suite, it's important to have precise reasoning on all steps.

(btw: the style of argument, bullet points, and "key points" summary makes this response looks very AI generated to me 🤔 no offense if it isn't)
